add_subdirectory(OptionalSgpr)
include("${CMAKE_CURRENT_LIST_DIR}/NormalizedLoad/registration.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ScalarTermination/registration.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/OneDimensionalGatherOffset/registration.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/UnnormalizedSampler/registration.cmake")
